### ISSUE TITLE
1.0.0 Release

### ISSUE THREAD

**Issue by Guz013** [loreddev/LoredMarkdown#7]
Here are the listed features of the new Lored's Markdown (formerly [Marknow](https://github.com/LoredDev/MarkNow)) project.

### Banners:

- [ ] Banner library
  - [ ] Banner Object API #13
  - [ ] Layouts #8 
    - [ ] Horizontal
    - [ ] Vertical
    - [ ] Left-to-Right
    - [ ] Right-to-Left
  - [ ] Backgrounds
    - [ ] Solid color
    - [ ] Image (link and/or from Unsplash)
    - [ ] Image with color gradient/mask
    - [ ] Gradient
    - [ ] Transparent
  - [ ] Icons
    - [ ] Search from icônes
    - [ ] Link to SVG icon
    - [ ] Without icon
  
- [ ] REST API ("reflecting" the Banner Object API) #14
  - [ ] Endpoint that responses with the banner SVG or image
  - [ ] Endpoint to response to the form submission of the front-end. Updating the interface without JavaScript on the client.
 
- [ ] Front-end
  - [x] Mock the design on Penpot #9
  - [ ] Form for control of each banner aspect #10
  - [ ] Simple form submission, using the REST API (without JavaScript) #11
  - [ ] JavaScript enhancement, automatic re-render the banner when the values change on the form #12
